/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "gwen_parser_element.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef GWEN_PARSER_ELEMENT_P_H
#define GWEN_PARSER_ELEMENT_P_H

#include "gwen_parser_element.h"


#ifdef __cplusplus
extern "C" {
#endif

struct GWEN_PARSER_ELEMENT {
  GWEN_LIST_ELEMENT(GWEN_PARSER_ELEMENT)
  GWEN_TREE_ELEMENT(GWEN_PARSER_ELEMENT)
  int _refCount;
  uint32_t flags;
  GWEN_PARSER_ELEMENT_TYPE elementType;
  char *name;
  char *type;
  char *dbName;
  int minOccurs;
  int maxOccurs;
  int minSize;
  int maxSize;
  char *data;
  uint32_t runtimeFlags; /* volatile */
};

#ifdef __cplusplus
}
#endif

#endif

