/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "gwen_parser_element.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef GWEN_PARSER_ELEMENT_H
#define GWEN_PARSER_ELEMENT_H


#ifdef __cplusplus
extern "C" {
#endif

/* define GWEN_PARSER_ELEMENT_RTFLAGS */


/* define GWEN_PARSER_ELEMENT_FLAGS */


/* needed system headers */
#include <gwenhywfar/types.h>
#include <gwenhywfar/list1.h>
#include <gwenhywfar/list2.h>
#include <gwenhywfar/tree.h>
#include <gwenhywfar/db.h>

/* pre-headers */
#include <gwenhywfar/gwenhywfarapi.h>

typedef struct GWEN_PARSER_ELEMENT GWEN_PARSER_ELEMENT;
GWEN_LIST_FUNCTION_LIB_DEFS(GWEN_PARSER_ELEMENT, GWEN_ParserElement, GWENHYWFAR_API)
GWEN_LIST2_FUNCTION_LIB_DEFS(GWEN_PARSER_ELEMENT, GWEN_ParserElement, GWENHYWFAR_API)
GWEN_TREE_FUNCTION_LIB_DEFS(GWEN_PARSER_ELEMENT, GWEN_ParserElement, GWENHYWFAR_API)


typedef enum {
  GWEN_ParserElementType_Unknown = -1,
  GWEN_ParserElementType_Element,
  GWEN_ParserElementType_Attribute,
  GWEN_ParserElementType_Data,
  GWEN_ParserElementType_Choice
} GWEN_PARSER_ELEMENT_TYPE;


/* post-headers */
#include <gwenhywfar/gwen_parser_element_fns.h>


GWENHYWFAR_API GWEN_PARSER_ELEMENT_TYPE GWEN_ParserElementType_fromString(const char *p_s);

GWENHYWFAR_API const char *GWEN_ParserElementType_toString(GWEN_PARSER_ELEMENT_TYPE p_i);

/** Constructor. */
GWENHYWFAR_API GWEN_PARSER_ELEMENT *GWEN_ParserElement_new(void);

/** Destructor. */
GWENHYWFAR_API void GWEN_ParserElement_free(GWEN_PARSER_ELEMENT *p_struct);

GWENHYWFAR_API void GWEN_ParserElement_Attach(GWEN_PARSER_ELEMENT *p_struct);

GWENHYWFAR_API GWEN_PARSER_ELEMENT *GWEN_ParserElement_dup(const GWEN_PARSER_ELEMENT *p_struct);

GWENHYWFAR_API GWEN_PARSER_ELEMENT *GWEN_ParserElement_copy(GWEN_PARSER_ELEMENT *p_struct, const GWEN_PARSER_ELEMENT *p_src);

/** Getter.
 * Use this function to get the member "flags"
*/
GWENHYWFAR_API uint32_t GWEN_ParserElement_GetFlags(const GWEN_PARSER_ELEMENT *p_struct);

/** Getter.
 * Use this function to get the member "elementType"
*/
GWENHYWFAR_API GWEN_PARSER_ELEMENT_TYPE GWEN_ParserElement_GetElementType(const GWEN_PARSER_ELEMENT *p_struct);

/** Getter.
 * Use this function to get the member "name"
*/
GWENHYWFAR_API const char *GWEN_ParserElement_GetName(const GWEN_PARSER_ELEMENT *p_struct);

/** Getter.
 * Use this function to get the member "type"
*/
GWENHYWFAR_API const char *GWEN_ParserElement_GetType(const GWEN_PARSER_ELEMENT *p_struct);

/** Getter.
 * Use this function to get the member "dbName"
*/
GWENHYWFAR_API const char *GWEN_ParserElement_GetDbName(const GWEN_PARSER_ELEMENT *p_struct);

/** Getter.
 * Use this function to get the member "minOccurs"
*/
GWENHYWFAR_API int GWEN_ParserElement_GetMinOccurs(const GWEN_PARSER_ELEMENT *p_struct);

/** Getter.
 * Use this function to get the member "maxOccurs"
*/
GWENHYWFAR_API int GWEN_ParserElement_GetMaxOccurs(const GWEN_PARSER_ELEMENT *p_struct);

/** Getter.
 * Use this function to get the member "minSize"
*/
GWENHYWFAR_API int GWEN_ParserElement_GetMinSize(const GWEN_PARSER_ELEMENT *p_struct);

/** Getter.
 * Use this function to get the member "maxSize"
*/
GWENHYWFAR_API int GWEN_ParserElement_GetMaxSize(const GWEN_PARSER_ELEMENT *p_struct);

/** Getter.
 * Use this function to get the member "data"
*/
GWENHYWFAR_API const char *GWEN_ParserElement_GetData(const GWEN_PARSER_ELEMENT *p_struct);

/** Getter.
 * Use this function to get the member "runtimeFlags"
*/
GWENHYWFAR_API uint32_t GWEN_ParserElement_GetRuntimeFlags(const GWEN_PARSER_ELEMENT *p_struct);

/** Setter.
 * Use this function to set the member "flags"
*/
GWENHYWFAR_API void GWEN_ParserElement_SetFlags(GWEN_PARSER_ELEMENT *p_struct, uint32_t p_src);

/** Add flags.
 * Use this function to add flags to the member "flags"
*/
GWENHYWFAR_API void GWEN_ParserElement_AddFlags(GWEN_PARSER_ELEMENT *p_struct, uint32_t p_src);

/** Sub flags.
 * Use this function to sub flags from the member "flags"
*/
GWENHYWFAR_API void GWEN_ParserElement_SubFlags(GWEN_PARSER_ELEMENT *p_struct, uint32_t p_src);

/** Setter.
 * Use this function to set the member "elementType"
*/
GWENHYWFAR_API void GWEN_ParserElement_SetElementType(GWEN_PARSER_ELEMENT *p_struct, GWEN_PARSER_ELEMENT_TYPE  p_src);

/** Setter.
 * Use this function to set the member "name"
*/
GWENHYWFAR_API void GWEN_ParserElement_SetName(GWEN_PARSER_ELEMENT *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "type"
*/
GWENHYWFAR_API void GWEN_ParserElement_SetType(GWEN_PARSER_ELEMENT *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "dbName"
*/
GWENHYWFAR_API void GWEN_ParserElement_SetDbName(GWEN_PARSER_ELEMENT *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "minOccurs"
*/
GWENHYWFAR_API void GWEN_ParserElement_SetMinOccurs(GWEN_PARSER_ELEMENT *p_struct, int p_src);

/** Setter.
 * Use this function to set the member "maxOccurs"
*/
GWENHYWFAR_API void GWEN_ParserElement_SetMaxOccurs(GWEN_PARSER_ELEMENT *p_struct, int p_src);

/** Setter.
 * Use this function to set the member "minSize"
*/
GWENHYWFAR_API void GWEN_ParserElement_SetMinSize(GWEN_PARSER_ELEMENT *p_struct, int p_src);

/** Setter.
 * Use this function to set the member "maxSize"
*/
GWENHYWFAR_API void GWEN_ParserElement_SetMaxSize(GWEN_PARSER_ELEMENT *p_struct, int p_src);

/** Setter.
 * Use this function to set the member "data"
*/
GWENHYWFAR_API void GWEN_ParserElement_SetData(GWEN_PARSER_ELEMENT *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "runtimeFlags"
*/
GWENHYWFAR_API void GWEN_ParserElement_SetRuntimeFlags(GWEN_PARSER_ELEMENT *p_struct, uint32_t p_src);

/** Add flags.
 * Use this function to add flags to the member "runtimeFlags"
*/
GWENHYWFAR_API void GWEN_ParserElement_AddRuntimeFlags(GWEN_PARSER_ELEMENT *p_struct, uint32_t p_src);

/** Sub flags.
 * Use this function to sub flags from the member "runtimeFlags"
*/
GWENHYWFAR_API void GWEN_ParserElement_SubRuntimeFlags(GWEN_PARSER_ELEMENT *p_struct, uint32_t p_src);

/* list1 functions */
GWENHYWFAR_API GWEN_PARSER_ELEMENT_LIST *GWEN_ParserElement_List_dup(const GWEN_PARSER_ELEMENT_LIST *p_src);

GWENHYWFAR_API void GWEN_ParserElement_ReadDb(GWEN_PARSER_ELEMENT *p_struct, GWEN_DB_NODE *p_db);

GWENHYWFAR_API int GWEN_ParserElement_WriteDb(const GWEN_PARSER_ELEMENT *p_struct, GWEN_DB_NODE *p_db);

GWENHYWFAR_API GWEN_PARSER_ELEMENT *GWEN_ParserElement_fromDb(GWEN_DB_NODE *p_db);

GWENHYWFAR_API int GWEN_ParserElement_toDb(const GWEN_PARSER_ELEMENT *p_struct, GWEN_DB_NODE *p_db);

#ifdef __cplusplus
}
#endif

#endif

