/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "oh_institute_spec.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef OH_INSTITUTE_SPEC_H
#define OH_INSTITUTE_SPEC_H


#ifdef __cplusplus
extern "C" {
#endif

/* needed system headers */
#include <gwenhywfar/types.h>
#include <gwenhywfar/list1.h>
#include <gwenhywfar/list2.h>
#include <gwenhywfar/db.h>

/* pre-headers */
#include <aqofxconnect/aqofxconnect.h>

typedef struct OH_INSTITUTE_SPEC OH_INSTITUTE_SPEC;
GWEN_LIST_FUNCTION_LIB_DEFS(OH_INSTITUTE_SPEC, OH_InstituteSpec, AQOFXCONNECT_API)
GWEN_LIST2_FUNCTION_LIB_DEFS(OH_INSTITUTE_SPEC, OH_InstituteSpec, AQOFXCONNECT_API)


/* post-headers */
#include <aqofxconnect/oh_institute_spec_fns.h>


/** Constructor. */
AQOFXCONNECT_API OH_INSTITUTE_SPEC *OH_InstituteSpec_new(void);

/** Destructor. */
AQOFXCONNECT_API void OH_InstituteSpec_free(OH_INSTITUTE_SPEC *p_struct);

AQOFXCONNECT_API void OH_InstituteSpec_Attach(OH_INSTITUTE_SPEC *p_struct);

AQOFXCONNECT_API OH_INSTITUTE_SPEC *OH_InstituteSpec_dup(const OH_INSTITUTE_SPEC *p_struct);

AQOFXCONNECT_API OH_INSTITUTE_SPEC *OH_InstituteSpec_copy(OH_INSTITUTE_SPEC *p_struct, const OH_INSTITUTE_SPEC *p_src);

/** Getter.
 * Use this function to get the member "id"
*/
AQOFXCONNECT_API int OH_InstituteSpec_GetId(const OH_INSTITUTE_SPEC *p_struct);

/** Getter.
 * Use this function to get the member "name"
*/
AQOFXCONNECT_API const char *OH_InstituteSpec_GetName(const OH_INSTITUTE_SPEC *p_struct);

/** Setter.
 * Use this function to set the member "id"
*/
AQOFXCONNECT_API void OH_InstituteSpec_SetId(OH_INSTITUTE_SPEC *p_struct, int p_src);

/** Setter.
 * Use this function to set the member "name"
*/
AQOFXCONNECT_API void OH_InstituteSpec_SetName(OH_INSTITUTE_SPEC *p_struct, const char *p_src);

/* list1 functions */
AQOFXCONNECT_API OH_INSTITUTE_SPEC_LIST *OH_InstituteSpec_List_dup(const OH_INSTITUTE_SPEC_LIST *p_src);

AQOFXCONNECT_API void OH_InstituteSpec_ReadDb(OH_INSTITUTE_SPEC *p_struct, GWEN_DB_NODE *p_db);

AQOFXCONNECT_API int OH_InstituteSpec_WriteDb(const OH_INSTITUTE_SPEC *p_struct, GWEN_DB_NODE *p_db);

AQOFXCONNECT_API OH_INSTITUTE_SPEC *OH_InstituteSpec_fromDb(GWEN_DB_NODE *p_db);

AQOFXCONNECT_API int OH_InstituteSpec_toDb(const OH_INSTITUTE_SPEC *p_struct, GWEN_DB_NODE *p_db);

AQOFXCONNECT_API OH_INSTITUTE_SPEC *OH_InstituteSpec_List_GetById(const OH_INSTITUTE_SPEC_LIST *p_list, int p_cmp);

#ifdef __cplusplus
}
#endif

#endif

